name: CI/CD with AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build and Deploy to Elastic Beanstalk
      run: |
        npm run build
        aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}
        aws elasticbeanstalk create-application-version --application-name "blogspostsapp" --version-label $GITHUB_SHA --source-bundle S3Bucket="elasticbeanstalk-ap-south-1-940035950318",S3Key="$GITHUB_SHA.zip"
        aws elasticbeanstalk update-environment --environment-name "blogspostsapp" --version-label $GITHUB_SHA        
